# `dep` does not seem to like this empty directory in the Kubernetes
# repository.
ignored = ["k8s.io/kubernetes/pkg/api"]

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "google.golang.org/api"
  revision = "373a4c220f5c90e5b7ff7101779c5be385d171be"

[[constraint]]
  name = "k8s.io/api"
  revision = "release-1.10"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.9.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "9c40f5b5a622c61c2e37efd37bf136d174d6799a"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
#
# Kubernetes is currently vendoring a non-released version. One of the
# symbols needed is no longer there in the released tag.
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
[[override]]
  name = "google.golang.org/api"
  revision = "7f657476956314fee258816aaf81c0ff65cf8bee"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[[constraint]]
  branch = "master"
  name = "k8s.io/cluster-registry"
