# `dep` does not seem to like this empty directory in the Kubernetes
# repository.
ignored = ["k8s.io/kubernetes/pkg/api"]

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.1"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
#
# Kubernetes is currently vendoring a non-released version. One of the
# symbols needed is no longer there in the released tag.
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

# This needs to be an override as it is a non-direct dependency and will not be
# considered by `dep` as a constraint.
[[override]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
  version="v1.4.7"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.10"
